### ISSUE TITLE
Remove out-of-things dependency

### ISSUE THREAD

**Issue by tolauwae** [TOPLLab/WARDuino-VSCode#22]
- [x] `toBinary` in [WOODState](https://github.com/TOPLLab/WARDuino-VSCode/blob/master/src/State/WOODState.ts#L14)
- [x] `specifyProxyCalls` in [WOODDebugBridge](https://github.com/TOPLLab/WARDuino-VSCode/blob/master/src/DebugBridges/WOODDebugBridge.ts#L52)

**Comment by carllocos** [comment]
Banch enhancement/22 implements the missing functionality. I also already merged it into the develop branch.
