### ISSUE TITLE
Version 0.3.0 breaks on vs code v1.79

### ISSUE THREAD

**Issue by tolauwae** [TOPLLab/WARDuino-VSCode#96]
**MAJOR ISSUE**

The plugin can't step anymore, starting at vs code 1.79 (May 2023 release). 

Plugin version 0.2.3 still works with the latest vs code release. In other words, version 0.3.0 (PR #88) introduced the problem.

@carllocos From a quick debug I couldn't see anything going wrong. I think we may have no other choice than to just try and find the breaking commit with `git bisect`, even tho its like 400 commits ... _(the 100 or so latch commits can be ignored)_
But maybe you have some further insight into your code that can narrow it down more?

**Comment by carllocos** [comment]
Fix in PR https://github.com/TOPLLab/WARDuino-VSCode/pull/101
