### ISSUE TITLE
Current line not updated at breakpoint hit

### ISSUE THREAD

**Issue by tolauwae** [TOPLLab/WARDuino-VSCode#97]
In version 0.3.0 at a breakpoint hit, the current line isn't updated.

@carllocos I do see a dump instruction in the debug console. But no StoppedEvent in the debugsession.ts is ever sent for breakpoints, like it was before. Thoughts?

**Comment by tolauwae** [comment]
Never mind, I broke this when adding sourcemapping for AssemblyScript. My bad.

**Comment by tolauwae** [comment]
The refactor of the code is heavily tied together with the communication library, so it is hard to do without making progress there simultatiously. With 500 commits the last PR was large enough already and had to be pushed as quickely as possible, because it was holding up progress, such as the refactor and sourcemapping. It wasn't at all the goal to make the code perfect, that would have been impossible in the timeframe.

Nevertheless, it don't think the code is anymore understandable, or the structure has improved in any meaningful way compared to the code after MPLR. So I still think that we need to rewrite from scratch in the comms library as much as possible and not shy away from rethinking the interface and structure, such as using Event Emitters. But we can certainly make even larger changes.

One of those changes clearly has to be how the step works, it is already much better in a sense due to the Event Emitters. The step now includes the refresh with a nice async await, and doesn't have to pass through the parser utils first.

So perhaps it is not more confusing, but certainly not less so. The fact that the refresh function doesn't trigger an update of the vs code state, is highly confusing and not at all the behaviour one would expect. I think this increases the chance of bugs and mistakes, and so has to be refactored. That is why I opened issue #99.

**Comment by carllocos** [comment]
I don't have a problem with the refactoring. I agree with that. I just don't appreciate the way you raise your concern. You are essentially dropping "Amazingly you managed to make it even worse". I'm a human I still have feelings :p. Just keep that in mind next time.

**Comment by tolauwae** [comment]
Yes that was untactful. It was certainly not meant as a comment on your work, or yourself. I was dissappointed that after so much work getting the last merged done, the code had gotten even more complicated imo with a lot of dead code. Ofcourse that is not unusual, god knows I have introduced enough code smells and technical debt myself.

The fact that the whole merge took this long has been very stressful with the upcoming demo, and has kept me from many other projects I need to work on. However that is not an excuse for expressing my disappointment in the way that I did. I understand that "amazingly" comes across harsher than intended. I apologise for being rude.

In future if you ever feel this way again about something I say or write, I would appreciate it if you can take this up with me in person rather than a public thread on GitHub. I am always willing to talk face to face, and perfectly happen to receive criticism.
